include: package:very_good_analysis/analysis_options.10.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    use_if_null_to_convert_nulls_to_bools: false
    unnecessary_parenthesis: false
    sort_pub_dependencies: false