// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    birds,
    breedingPairs,
    broods,
    eggs,
    contacts,
    finances,
    financeCategories,
    species,
    cages,
    birdColors,
  ];
  late final Shape0 birds = Shape0(
      source: i0.VersionedTable(
        entityName: 'birds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 breedingPairs = Shape1(
      source: i0.VersionedTable(
        entityName: 'breeding_pairs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_32,
          _column_7,
          _column_33,
          _column_34,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 broods = Shape2(
      source: i0.VersionedTable(
        entityName: 'broods',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_35,
          _column_7,
          _column_33,
          _column_34,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 eggs = Shape3(
      source: i0.VersionedTable(
        entityName: 'eggs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_36,
          _column_37,
          _column_38,
          _column_10,
          _column_39,
          _column_40,
          _column_11,
          _column_41,
          _column_1,
          _column_3,
          _column_7,
          _column_2,
          _column_42,
          _column_21,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 contacts = Shape4(
      source: i0.VersionedTable(
        entityName: 'contacts',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 finances = Shape5(
      source: i0.VersionedTable(
        entityName: 'finances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_56,
          _column_57,
          _column_58,
          _column_21,
          _column_59,
          _column_60,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 financeCategories = Shape6(
      source: i0.VersionedTable(
        entityName: 'finance_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_61,
          _column_62,
          _column_63,
          _column_21,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 species = Shape7(
      source: i0.VersionedTable(
        entityName: 'species',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
          _column_68,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 cages = Shape8(
      source: i0.VersionedTable(
        entityName: 'cages',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 birdColors = Shape9(
      source: i0.VersionedTable(
        entityName: 'bird_colors',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_76,
          _column_77,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ringnumber =>
      columnsByName['ringnumber']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get species =>
      columnsByName['species']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get father =>
      columnsByName['father']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mother =>
      columnsByName['mother']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cage =>
      columnsByName['cage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brood =>
      columnsByName['brood']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get laidAt =>
      columnsByName['laid_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hatchedAt =>
      columnsByName['hatched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fledgedAt =>
      columnsByName['fledged_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bornAt =>
      columnsByName['born_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get diedAt =>
      columnsByName['died_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get saleStatus =>
      columnsByName['sale_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get listedAt =>
      columnsByName['listed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get soldAt =>
      columnsByName['sold_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get askingPrice =>
      columnsByName['asking_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get finalPrice =>
      columnsByName['final_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get boughtAt =>
      columnsByName['bought_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get boughtPrice =>
      columnsByName['bought_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get boughtFrom =>
      columnsByName['bought_from']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get soldTo =>
      columnsByName['sold_to']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get owner =>
      columnsByName['owner']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get breeder =>
      columnsByName['breeder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unknownLifecycle =>
      columnsByName['unknown_lifecycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('ringnumber', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('species', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('color', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('sex', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
        defaultValue: const i1.CustomExpression('\'unknown\''));
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('father', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('mother', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('cage', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('brood', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('laid_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('hatched_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>('fledged_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>('born_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('died_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('sale_status', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'notForSale\'',
        defaultValue: const i1.CustomExpression('\'notForSale\''));
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>('listed_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>('sold_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>('asking_price', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>('final_price', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('bought_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>('bought_price', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('notes', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>('bought_from', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('sold_to', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('owner', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>('breeder', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>('unknown_lifecycle', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL CHECK (unknown_lifecycle IN (0, 1))');
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>('user', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('created', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('updated', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get father =>
      columnsByName['father']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mother =>
      columnsByName['mother']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cage =>
      columnsByName['cage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get start =>
      columnsByName['start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get end =>
      columnsByName['end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('father', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>('mother', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('status', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>('start', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>('end', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get breedingPair =>
      columnsByName['breeding_pair']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cage =>
      columnsByName['cage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get start =>
      columnsByName['start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get end =>
      columnsByName['end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>('breeding_pair', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brood =>
      columnsByName['brood']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get number =>
      columnsByName['number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get laidAt =>
      columnsByName['laid_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hatchedAt =>
      columnsByName['hatched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fertilizedAt =>
      columnsByName['fertilized_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get unfertilizedAt =>
      columnsByName['unfertilized_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fledgedAt =>
      columnsByName['fledged_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ringnumber =>
      columnsByName['ringnumber']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cage =>
      columnsByName['cage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get species =>
      columnsByName['species']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get birdId =>
      columnsByName['bird_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>('brood', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>('number', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>('laid_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>('fertilized_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>('unfertilized_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('status', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'laid\'',
        defaultValue: const i1.CustomExpression('\'laid\''));
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>('bird_id', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cellPhoneNumber =>
      columnsByName['cell_phone_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get firstName =>
      columnsByName['first_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastName =>
      columnsByName['last_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get city =>
      columnsByName['city']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get country =>
      columnsByName['country']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get postalCode =>
      columnsByName['postal_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get website =>
      columnsByName['website']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isAppUser =>
      columnsByName['is_app_user']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>('number', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>('phone', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('cell_phone_number', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>('first_name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>('last_name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>('address', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>('city', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>('country', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>('postal_code', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>('website', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>('is_app_user', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_app_user IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bird =>
      columnsByName['bird']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>('category', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_58(String aliasedName) =>
    i1.GeneratedColumn<double>('amount', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>('bird', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>('date', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>('color', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>('kind', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get latName =>
      columnsByName['lat_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get incubationDays =>
      columnsByName['incubation_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fledgeDays =>
      columnsByName['fledge_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>('lat_name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>('image_url', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>('incubation_days', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>('fledge_days', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get depth =>
      columnsByName['depth']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get capacity =>
      columnsByName['capacity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>('width', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>('height', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>('depth', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>('location', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>('capacity', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hex =>
      columnsByName['hex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inheritance =>
      columnsByName['inheritance']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>('hex', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>('inheritance', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    birds,
    breedingPairs,
    broods,
    eggs,
    contacts,
    finances,
    financeCategories,
    species,
    cages,
    birdColors,
  ];
  late final Shape0 birds = Shape0(
      source: i0.VersionedTable(
        entityName: 'birds',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 breedingPairs = Shape1(
      source: i0.VersionedTable(
        entityName: 'breeding_pairs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_32,
          _column_7,
          _column_33,
          _column_34,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 broods = Shape2(
      source: i0.VersionedTable(
        entityName: 'broods',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_35,
          _column_7,
          _column_33,
          _column_34,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 eggs = Shape10(
      source: i0.VersionedTable(
        entityName: 'eggs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_36,
          _column_37,
          _column_38,
          _column_10,
          _column_39,
          _column_40,
          _column_11,
          _column_13,
          _column_41,
          _column_1,
          _column_3,
          _column_7,
          _column_2,
          _column_42,
          _column_21,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 contacts = Shape4(
      source: i0.VersionedTable(
        entityName: 'contacts',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 finances = Shape5(
      source: i0.VersionedTable(
        entityName: 'finances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_56,
          _column_57,
          _column_58,
          _column_21,
          _column_59,
          _column_60,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 financeCategories = Shape6(
      source: i0.VersionedTable(
        entityName: 'finance_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_61,
          _column_62,
          _column_63,
          _column_21,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 species = Shape7(
      source: i0.VersionedTable(
        entityName: 'species',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
          _column_68,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 cages = Shape8(
      source: i0.VersionedTable(
        entityName: 'cages',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 birdColors = Shape9(
      source: i0.VersionedTable(
        entityName: 'bird_colors',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_64,
          _column_76,
          _column_77,
          _column_21,
          _column_27,
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brood =>
      columnsByName['brood']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get number =>
      columnsByName['number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get laidAt =>
      columnsByName['laid_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hatchedAt =>
      columnsByName['hatched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fertilizedAt =>
      columnsByName['fertilized_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get unfertilizedAt =>
      columnsByName['unfertilized_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fledgedAt =>
      columnsByName['fledged_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get diedAt =>
      columnsByName['died_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ringnumber =>
      columnsByName['ringnumber']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cage =>
      columnsByName['cage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get species =>
      columnsByName['species']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get birdId =>
      columnsByName['bird_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
    ));
